if (CMAKE_BUILD_TYPE MATCHES "Debug")
    set(DebugCompilerFlags -Wall -Wextra -Wpedantic -g -O0)
    message(STATUS "Target compiler flags are: ${DebugCompilerFlags}")
    add_compile_options(${DebugCompilerFlags})
elseif (CMAKE_BUILD_TYPE MATCHES "Release")
    set(DebugCompilerFlags -Wall -Wextra -Wpedantic -O2)
    message(STATUS "Target compiler flags are: ${DebugCompilerFlags}")
    add_compile_options(${DebugCompilerFlags})
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(RESOURCE_FOLDER "${CMAKE_CURRENT_SOURCE_DIR}/resource")
